### ISSUE TITLE
Pass environment variables when render task definition

### ISSUE THREAD

**Issue by dspv** [aws-actions/amazon-ecs-render-task-definition#112]
Would be great to have the ability to change environment variables when rending a new task definition. I cannot find any other chance how to do it :)

**Comment by utkarshcmu** [comment]
+1

**Comment by Misterio77** [comment]
I had  this same need and tried to get it working.

WIP, still testing: https://github.com/Misterio77/amazon-ecs-render-task-definition

**Comment by amazreech** [comment]
Closing older Issue. This should be supported as part of [PR114](https://github.com/aws-actions/amazon-ecs-render-task-definition/pull/114)
