### ISSUE TITLE
Unexpected token ':'

### ISSUE THREAD

**Issue by gethumanfoundation** [aws-actions/amazon-ecs-render-task-definition#118]
I'm getting an error when I get to this section?

Run aws-actions/amazon-ecs-render-task-definition@97587c9d45a4930bf0e3da8dd2feb2a463cf4a3a
  with:
    task-definition: ecs-task-def-dev
    container-name: dango-github-actions-dev
    image: ***.dkr.ecr.us-east-2.amazonaws.com/django-github-actions-dev:bea5a7b64651a11221551d8a7fbcbe8d4ba9d4ed
  env:
    AWS_REGION: us-east-2
    ECR_REPOSITORY: django-github-actions-dev
    ECS_SERVICE: django-github-actions-dev-service
    ECS_CLUSTER: django-github-actions-dev
    ECS_TASK_DEFINITION: ecs-task-def-dev
    CONTAINER_NAME: dango-github-actions-dev
    DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1
    SECRET_KEY: foo
    AWS_DEFAULT_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Error: Unexpected token ':'

**Comment by gethumanfoundation** [comment]
Had to do with the formatting of the task definition json file name.

**Comment by ComfyDust** [comment]
Ran into this too. Had to add a ".json" extension to the filename I was using.
