### ISSUE TITLE
How replace the variables in the JSON file through the YML file?

### ISSUE THREAD

**Issue by Moodguo** [aws-actions/amazon-ecs-render-task-definition#122]
Hi, task definition except to specifying ['task definition ',' container name ',' image '], what other valid inputs are available?    

- name: Render Amazon ECS task definition
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: web
        image: amazon/amazon-ecs-sample:latest
       <"hostport ?">
If I want to replace the variables in the JSON file through the YML file, 
for example:  replacing "hostport" in JSON file in YML file 
      "portMappings": [
        {
          "hostPort": 80,
          "protocol": "tcp",
          "containerPort": 80
        }

**Comment by paragbhingre** [comment]
Thank you @Moodguo for your query, we will get back to you as soon as we have the answer.

**Comment by paragbhingre** [comment]
Hello @Moodguo, I am attaching a link to the [document](https://github.com/aws-actions/amazon-ecs-render-task-definition/blob/master/action.yml) explaining the input and output of this particular AWS Github Action. As per the document you can only modify **'task definition ',' container name ',' image '**. Other variables can be modified directly in the task definition. I hope this answers your question. I am closing this issue for now please feel free to open this issue if you have any more questions.
