### ISSUE TITLE
Task definition json

### ISSUE THREAD

**Issue by nodesocket** [aws-actions/amazon-ecs-render-task-definition#13]
Sorry if this is a silly question, but does the task-definition json have to exist in the repo itself? Anyway to pull it dynamically from ECR and just update the image?

**Comment by clareliguori** [comment]
This action won't pull it down, but in a previous step you can do:
```
    - name: Download task def
      run: |
        aws ecs describe-task-definition --task-definition task-def-family --query taskDefinition > task-definition.json
```

**Comment by nodesocket** [comment]
Perfect that worked as expected.

**Comment by DanielLaberge** [comment]
This ought to be documented in the repo's README. I suspect many devs just want this.
