### ISSUE TITLE
Changing other values, e.g. executionRoleArn

### ISSUE THREAD

**Issue by skinofstars** [aws-actions/amazon-ecs-render-task-definition#19]
I wonder if there's a way for allowing this to update other values in the definition, e.g. executionRoleArn

The executionRoleArn includes the account ID, which may not be ideal to include in a public repo.

**Comment by clareliguori** [comment]
I'm open to contributions! :)

FWIW both the executionRoleArn and taskRoleArn can actually be just the role name.  ECS will fill in the account ID server-side when the task definition is registered.
```
  "executionRoleArn": "my-execution-role-name",
  "taskRoleArn": "my-task-role-name",
```

**Comment by skinofstars** [comment]
What open source maintainer isn't looking for patches? Alas, you've solved my problem perfectly. 😁
