### ISSUE TITLE
set-output command is deprecated

### ISSUE THREAD

**Issue by bruno-chavez** [aws-actions/amazon-ecs-render-task-definition#198]
Hi using version `aws-actions/amazon-ecs-render-task-definition@v1` and getting the following warning on every run of the action:

Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Not sure if there is a plan for the deprecation of the command, but hopefully this issue sets it into motion.

**Comment by blairjanis** [comment]
This is me showing my ignorance ... I'm still getting this warning message using `aws-actions/amazon-ecs-render-task-definition@v1`.  Do I need to modify the `@v1` and if so, what version should it be?

**Comment by dkhaye** [comment]
@blairjanis the fix PR #205 is not merged in yet, much less deployed.

**Comment by shmokmt** [comment]
#205 is merged but not released yet.

**Comment by chrblabla** [comment]
@iamhopaul123 What does it take to get this released?

**Comment by myorb-github-service** [comment]
Can you create the new tag for that please 
Using amazon-ecs-render-task-definition@v1 still  getting the "set-outputcommand is deprecated and"

**Comment by donfirst** [comment]
Has been fixed - confirmed  that it's work  :-)
