### ISSUE TITLE
Validation errors in task-definition.json

### ISSUE THREAD

**Issue by ndp03** [aws-actions/amazon-ecs-render-task-definition#2]
Hi 

I setup a simple test NodeJS project and try to use GitHub Actions to deploy ECR, ECS. The build and push to ECR step executed successfully. However, this action failed, i got these validations errors :

~~~
Run aws-actions/amazon-ecs-deploy-task-definition@v1
  with:
    task-definition: /home/runner/work/_temp/task-definition-3348qyZ6U3Tq2Is5.json
    service: xxx
    cluster: xxx
    wait-for-service-stability: true
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_DEFAULT_REGION: ap-southeast-2
    AWS_REGION: ap-southeast-2
##[error]There were 5 validation errors:
* UnexpectedParameter: Unexpected key 'compatibilities' found in params
* UnexpectedParameter: Unexpected key 'taskDefinitionArn' found in params
* UnexpectedParameter: Unexpected key 'requiresAttributes' found in params
* UnexpectedParameter: Unexpected key 'revision' found in params
* UnexpectedParameter: Unexpected key 'status' found in params
~~~
The content of task-definition.json is a direct copy-paste from AWS Console. 

Is this because this action is not up to date or am I missing something here?

Many thanks,

**Comment by clareliguori** [comment]
Those attributes are part of the output of the DescribeTaskDefinition API and are not valid for the input to the RegisterTaskDefinition API. For example, the "revision" and "status" attributes are computed by ECS when the task definition is registered and cannot be provided.

Simply remove those attributes from the file, and the action should successfully register the task definition.
