### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by harikrishnatrkv** [aws-actions/amazon-ecs-render-task-definition#218]
Getting the following warning  while using  "aws-actions/amazon-ecs-render-task-definition@v1"

Run aws-actions/amazon-ecs-render-task-definition@v1

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: `https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/````

**Comment by bidossessi** [comment]
Duplicate of #198, expected to be fixed by #205, IIUC.

**Comment by myorb-github-service** [comment]
Still doesn't work  :-(

**Comment by iamhopaul123** [comment]
Hello everyone. Sorry for the inconvenience. The security patch should be included in the [latest release](https://github.com/aws-actions/amazon-ecs-render-task-definition/releases/tag/v1.1.3).

**Comment by iamhopaul123** [comment]
Closing the issue for now.
