### ISSUE TITLE
Adding support for `dockerLabels` in task

### ISSUE THREAD

**Issue by johnseekins-pathccm** [aws-actions/amazon-ecs-render-task-definition#272]
ECS Fargate doesn't propagate labels as effectively as ECS on EC2, so being able to propagate labels down to containers using this action would be nice.

This has been attempted before with no real response: https://github.com/aws-actions/amazon-ecs-render-task-definition/pull/138. Is it possible this could get done?

**Comment by amazreech** [comment]
This feature should be released with PR#274 in Release [1.2.0](https://github.com/aws-actions/amazon-ecs-render-task-definition/compare/v1.1.3...v1.2.0).
