### ISSUE TITLE
dockers-labels not working

### ISSUE THREAD

**Issue by ShreyAmbesh** [aws-actions/amazon-ecs-render-task-definition#277]
I was waiting for the PR #274 to be merged but it doesn't look like it's working. 
"docker-labels" is not appearing as a valid input.
<img width="711" alt="image" src="https://github.com/aws-actions/amazon-ecs-render-task-definition/assets/31286953/28d98d7f-9838-4909-b761-1ea94543562a">

The documentation on the marketplace also differs for the action on default page and version selected page
On the default [landing page](https://github.com/marketplace/actions/amazon-ecs-render-task-definition-action-for-github-actions) the Readme has the docker-labels in the examples whereas when version is selected as version 1 which is the only available version [the page](https://github.com/marketplace/actions/amazon-ecs-render-task-definition-action-for-github-actions?version=v1) doesn't has docker-labels example.
Ideally both should be same as version 1 is the latest and the only version.

**Comment by ShreyAmbesh** [comment]
The documentation on the marketplace also differs for the action on default page and version selected page
On the default [landing page](https://github.com/marketplace/actions/amazon-ecs-render-task-definition-action-for-github-actions) the Readme has the docker-labels in the examples whereas when version is selected as version 1 which is the only available version [the page](https://github.com/marketplace/actions/amazon-ecs-render-task-definition-action-for-github-actions?version=v1) doesn't has docker-labels example.
Ideally both should be same as version 1 is the latest and the only version.

**Comment by ShreyAmbesh** [comment]
@johnseekins-pathccm Can you please help me with this?

**Comment by johnseekins-pathccm** [comment]
They haven't cut a new release. It's working for me if I use 
```
      uses: aws-actions/amazon-ecs-render-task-definition@master
```

**Comment by ShreyAmbesh** [comment]
@johnseekins-pathccm Thanks for the help.

**Comment by johnseekins-pathccm** [comment]
If that solves your problem, I'd encourage you to close the issue.
