### ISSUE TITLE
Warning - Task definition file will be used.

### ISSUE THREAD

**Issue by ChaseC-Piere** [aws-actions/amazon-ecs-render-task-definition#318]
We're experiencing an issue when deploying to our dev environment through GitHub Actions which is blocking us from rolling any new updates. The deployment is unable issue task variables making our app unable to access key secure values (url, API keys, etc.). Below is the message we get for every deployment to this environment regardless of if that specific code deployment worked in the past. We've tried rolling code back & previously successfully deployments back to June with the same results.

I'm trying to figure out why this is happening all of the sudden but so far we have made little progress toward a solution. Here's what I've tried,

1.) Rolled back code to our "main" or what's on production (same error)
2.) Re-attempt to roll back to a previously successful build (same error)
3.) Another co-worker re-deployed a previously successful build on his end (same error)
4.) Updated deployment package to newer version (new result relating to render deployment script)
![Screenshot 2024-08-09 at 1 19 00 PM](https://github.com/user-attachments/assets/3a12c578-21b1-455b-bedf-58fb0bc55e64)

**Comment by vcatalano** [comment]
I just noticed this message showing up for our deployments today. This is just a warning message though and should not be impacting the actual deployment. Are you sure there are no other error occurring in your case?

**Comment by ChaseC-Piere** [comment]
I'm not 100% but I've rolled back deployment to a version from over a month ago that worked and I'm getting the same warning and issue.

**Comment by amazreech** [comment]
Hi @ChaseC-Piere,

I am wondering if you are seeing this issue with the latest release `v.1.5.0` the render-task-definition repository. Would it be possible to try and see if this works with `v.1.4.0` version of render-task-definition repository? 

Also, is there any other errors or logs you could share related to this?

The warning messages you are seeing are expected and part of the latest release `v1.5.0` release of the render-task-definition repository. They simply indicate that you are using a task definition file.

**Comment by kg-aws** [comment]
Hi @ChaseC-Piere - Has there been any update/progress here with `v1.4.0`? If you think the issue is with the latest version of this repository, any logs or error messages that can confirm the same would be helpful for us to debug the issue.

**Comment by ChaseC-Piere** [comment]
Hi Kishan,

Rolling back to v1.4.0 did fix our deploy script issue. Thank you!

From: Kishan Gajjar - AWS ***@***.***>
Date: Monday, August 26, 2024 at 6:28 AM
To: aws-actions/amazon-ecs-render-task-definition ***@***.***>
Cc: Chase Cabrera ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-actions/amazon-ecs-render-task-definition] Warning - Task definition file will be used. (Issue #318)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @ChaseC-Piere<https://github.com/ChaseC-Piere> - Has there been any update/progress here with v1.4.0? If you think the issue is with the latest version of this repository, any logs or error messages that can confirm the same would be helpful for us to debug the issue.
