### ISSUE TITLE
container-name parameter not using outputs value

### ISSUE THREAD

**Issue by shurrman** [aws-actions/amazon-ecs-render-task-definition#35]
I have an action that renders task definition, trying to set both image and container-name parameters with the outputs of previous steps. While image parameter works ok, I get 
##[error]Input required and not supplied: container-name
for the container-name parameter when set like 
container-name: ${{ steps.step.outputs.CONTAINER }}

**Comment by hencrice** [comment]
Hey @shurrman . Based on https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L72, could it be that `steps.step.outputs.CONTAINER` is null or empty string?

**Comment by pkandasamy91** [comment]
Closing, please reopen if this is still an issue
