### ISSUE TITLE
Github commit sha passed to task-definition.json

### ISSUE THREAD

**Issue by jaedung** [aws-actions/amazon-ecs-render-task-definition#9]
Hi,

I build and tag a docker image with the latest github commit sha (e.g. 2880ba75d205f0a57055d369968b5afbac984fa9).

After the build is complete, I push the image to my AWS ECR.

In my task-definition.json, I need to specify the image (in this case, this will be AWS ECR image URL that contains the github commit sha). However, I can't the `commit sha` in my task-definition.json.

Is there a way to get the commit sha passed from github action yaml to task-definition.json?

Cheers,
Justin

**Comment by clareliguori** [comment]
Yes, you can use the `github.sha` variable in your workflow file:
`image: my_ecr_registry/my_ecr_repository:${{ github.sha }}`

This is a more complete example:
https://github.com/actions/starter-workflows/blob/master/ci/aws.yml#L54-L74
